apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx2
  labels:
    app: mynginx2
spec:
  replicas: 1
  template:
    metadata:
      name: mynginx2
      labels:
        app: mynginx2
    spec:
      containers:
        - name: mynginx2
          image: nginx
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: mynginx2
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx2
spec:
  selector:
    app: mynginx2
  ports:
    - port: 8080
      targetPort: 80
  type: NodePort